name: 'Tests'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  python-version: '3.9'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        uses: ./.github/actions/poetry-env-init
        with:
          python-version: ${{ env.python-version }}

      - name: 'Run lint check'
        run: poetry run poe lint-check

      - name: 'Run tests'
        run: poetry run poe test
